import Box from '@mui/material/Box';
import { useTheme } from '@mui/material/styles';
import { NextPage } from 'next';
import Head from 'next/head';

const DashboardPage: NextPage = () => {
  const theme = useTheme();
  return (
    <Box
      sx={{
        backgroundColor: theme.palette.mode === 'dark' ? theme.palette.background.paper : 'black',
        height: '0',
        width: '0'
      }}>
      <Head>
        <title>Telegram - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Box>
  )
}

export default DashboardPage;
